

/*
	*************************************************
	* @file:	spi_flash_uart_sender.c
	* Generated by Musa ÇUFALCI 2018
	* Copyright (c) Musa ÇUFALCI All rights reserved.
	*************************************************
*/


#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <sys/socket.h>
#include <netdb.h>
#include <stdint.h>

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/event_groups.h"

#include "esp_system.h"
#include "esp_wifi.h"
#include "esp_event_loop.h"
#include "esp_err.h"
#include "esp_log.h"
#include "esp_ota_ops.h"
#include "esp_partition.h"

#include "nvs.h"
#include "nvs_flash.h"

#include "driver/gpio.h"
#include "driver/uart.h"
#include "driver/i2s.h"

#include "sdkconfig.h"
#include "esp_spi_flash.h"
#include "rom/spi_flash.h"
#include "rom/uart.h"


#include "eprom.h"
#include "cJSON.h"
//***********************************************************************************************
#define UARTB_TXD (18)
#define UARTB_RXD (19)
#define UARTA_TXD (17)
#define UARTA_RXD (16)
#define LED1 25
#define LED2 26
#define DEFAULT_BAUD 921600

#define buton1 21 // buton1 mavi kablo
#define buton2 22 // buton2 sarý kablo

#define BUFFSIZE 128
#define UART_BUFFSIZE 256
#define delay(ms) (vTaskDelay(ms/portTICK_RATE_MS));
cJSON *FR_packet;
//char temp[BUFFSIZE]={0};
char temp[UART_BUFFSIZE]={0};

char temp2[1]={0};

//***********************************************************************************************


//----------------------------------------------------------------------------------------

void blink_led1_task(void *pvParameters)
{
    gpio_pad_select_gpio(LED1);
    gpio_pad_select_gpio(LED2);
    gpio_set_direction(LED1, GPIO_MODE_OUTPUT);
    gpio_set_direction(LED2, GPIO_MODE_OUTPUT);
    while(1) {
        gpio_set_level(LED1, 0);
        gpio_set_level(LED2, 0);
        delay(2000);
        gpio_set_level(LED1, 1);
        gpio_set_level(LED2, 1);
        delay(2000);
    }
}
//***********************************************************************************************


void Write_flash_Task(void *pvParameters)
{
	const char hexmap[] = {'0', '1', '2', '3', '4', '5', '6', '7',
						   '8', '9', 'A', 'B', 'C', 'D', 'E', 'F'};

	//UART1 configuration
	    const int uart_num1 = UART_NUM_1;
	    uart_config_t uart_config1 = {
	        .baud_rate = DEFAULT_BAUD,
	        .data_bits = UART_DATA_8_BITS,
	        .parity = UART_PARITY_DISABLE,
	        .stop_bits = UART_STOP_BITS_1,
	        .flow_ctrl = UART_HW_FLOWCTRL_DISABLE,    //UART_HW_FLOWCTRL_CTS_RTS,
	        .rx_flow_ctrl_thresh = 122,
	    };
	//----------------------------------------------------------------------------------------
	//Configure UART1 parameters
	    uart_param_config(uart_num1, &uart_config1);
	    uart_set_pin(uart_num1, UARTB_TXD, UARTA_RXD, UART_PIN_NO_CHANGE, UART_PIN_NO_CHANGE);
		uart_driver_install(uart_num1, UART_BUFFSIZE, 0, 0, NULL, 0);


	    int table_size = sizeof(eprom_table);
	    printf("table_sizeof: %d\r\n", table_size);

//	    uint32_t lastpacketsize = (uint32_t )(table_size % UART_BUFFSIZE);
//		printf("lastpacketsize: %d\r\n", lastpacketsize);

		int packet_count = (table_size / BUFFSIZE);
		printf("packet_count: %d\r\n", packet_count);

		int packet_count2 = 0;

		for (int j=0; j < table_size; j+=BUFFSIZE)
		{
			FR_packet=cJSON_CreateObject();
			cJSON_AddNumberToObject(FR_packet, "FC", packet_count2);
			memset(temp, 0, sizeof(temp));

			for (int i = 0; i < UART_BUFFSIZE / 2; ++i) {
				temp[2 * i]     = hexmap[(eprom_table[i + j] & 0xF0) >> 4];
				temp[2 * i + 1] = hexmap[eprom_table[i + j] & 0x0F];
		    }

//			for (int i = 0; i < BUFFSIZE; i++){
//				temp[i] = eprom_table[i + j];
//
//				sprintf(temp2, "%c", eprom_table[i+j]);
//				strcat(temp,temp2);
//			}
//			for (int i=0; i<BUFFSIZE; i++){
//			        	temp[i]=eprom_table[j];
//			        	//printf(" %02X", temp[i]);
//			        }

			printf("\nTemp: %s\r\n", temp);

//			printf("\ntemp: ");
//			for (int i = 0; i < BUFFSIZE; ++i)
//				printf("%02X", temp[i]);
//
//			printf("\r\n");

			cJSON_AddStringToObject(FR_packet, "FD", temp);
			char* rendered1 = cJSON_Print(FR_packet);
			char* rendered2 = cJSON_PrintUnformatted(FR_packet);

			cJSON* FD_JSON = cJSON_GetObjectItem(FR_packet, "FD");

//			printf("\nFD_JSON: %s\r\n", FD_JSON->valuestring);

			uart_write_bytes(uart_num1, rendered2, strlen(rendered2));
			printf("\n JSON: %s\r\n", rendered2);

			cJSON_Delete(FR_packet);
			cJSON_free(rendered1);
			cJSON_free(rendered2);

			printf("\n");
			packet_count2++;
			delay(10);
		}

	packet_count2 = 0;
	vTaskDelete(NULL);
}

//***********************************************************************************************
void app_main()
{
//	gpio_pad_select_gpio(buton1);
//	gpio_set_direction(buton1, GPIO_MODE_INPUT);

//	if (gpio_get_level(buton1)==0){

//	nvs_flash_init();
//	system_init();



// workaround: configure SPI flash size manually (2nd argument)
//SPIParamCfg(0x1540ef, 4*1024*1024, 64*1024, 4096, 256, 0xffff);


xTaskCreatePinnedToCore(&blink_led1_task, "blink_led1_task", 512, NULL, 5, NULL, 0);
xTaskCreatePinnedToCore(&Write_flash_Task, "Write_flash_Task", 4096, NULL, 10, NULL, 0);

//	}


//while(1){
//    delay(2000);
//    ESP_LOGI("main","heap:%d",xPortGetFreeHeapSize());
//    }
}


//***********************************************************************************************
